### ISSUE TITLE
marisolbrown.txt not in the correct location

### ISSUE THREAD

**Issue by philmcneely** [marisolbrown/V4Q#1]
please move to 
V4Q/Class11/TestTools1_Prework/marisolbrown.txt and camel case it

To do that, in your local file system, create the directory structure and move your file there.

cd V4Q
mkdir Class11
cd Class11
mkdir TestTools1_Prework
cd TestTools1_Prework
mv ../../marisolbrown.txt ./MarisolBrown.txt

**Comment by marisolbrown** [comment]
The File marisolbrown.txt was relocated to V4Q/Class11/TestTools1_Prework/MarisolBrown.txt and the file was changed to camel case by capitalizing the letters M and B to look like MarisolBrown.txt, with the following steps:

cd V4Q
mkdir Class11
cd Class11
mkdir TestTools1_Prework
cd TestTools1_Prework
mv ../../marisolbrown.txt ./MarisolBrown.txt
The marisolbrown.txt file in the root was deleted with the following code: 
$ git commit -m delete MarisolBrown.txt
